### ISSUE TITLE
Apply data normalization to the graph by using the context menu of the pyqtgraph library

### ISSUE THREAD

**Issue by grochot** [grochot/spinlab_measurement#41]

**Comment by Did-Mas** [comment]
I managed to add normalization to the context menu, but it requires modifications to the pyqtgraph module. To make these changes, I need the module to be added to the repository. I would prefer if @grochot could add the module. Once it's added, I will make the necessary modifications.

**Comment by grochot** [comment]
<img width="425" alt="Zrzut ekranu 2024-09-4 o 11 31 12" src="https://github.com/user-attachments/assets/18a0e805-f096-49b4-a611-463c306e2f3b">
Added normalize option to context menu. It is necessary to uninstall the pyqtgraph library and use the local version.

**Comment by Did-Mas** [comment]
Data is not normalized properly during measurement

**Comment by Did-Mas** [comment]
Fixed issue in commit c99207841993bc24aae082f13c8b506f47d8f871

Normalization did not work because the information about the normalization mode was not provided when creating a new curve. It was only applied after rechecking the checkbox in the context menu.
