### ISSUE TITLE
Add a continuous measurement option on the Quick Measurement tab

### ISSUE THREAD

**Issue by grochot** [grochot/spinlab_measurement#43]

**Comment by Did-Mas** [comment]
![image](https://github.com/user-attachments/assets/11d5cca6-3e3d-4b16-95f7-4af387f2b3c2)

Added continuous measurement mode in commit 30c885f0561d29d7c9bd36f6d3d7d10afffa452e

To take measurements, first choose the parameter values and press the 'Initialize' button. Then, press the 'Single' button for a single measurement or the 'Start' button for continuous mode. After every parameter change, press the 'Initialize' button.
