### ISSUE TITLE
Create a driver for Criomagentics gm-700 

### ISSUE THREAD

**Issue by grochot** [grochot/spinlab_measurement#48]

**Comment by Did-Mas** [comment]
I started implementing a driver for the device, and while it works, I've encountered an issue. The driver communicates with the device successfully, but if the communication is interrupted or stopped, it cannot be restored.

For example, after connecting the device to the PC and opening a session in PuTTY, I can communicate with the device without any problems. However, once I close the PuTTY session and try to open it again, I receive an error: "Unable to open connection to COM." Similarly, when I first connect the device, I can run the Python driver and receive a proper response. But if I try to run the driver again, I encounter a PyVISA error.
